sudo: false
language: python
python:
  - "3.5"
dist: trusty
env:
  matrix:
    - TOX_ENV=py27-core-stdlib
    - TOX_ENV=py34-core-stdlib
    - TOX_ENV=py35-core-stdlib
    - TOX_ENV=py27-core-gevent
    - TOX_ENV=py34-core-gevent
    - TOX_ENV=py35-core-gevent
    - TOX_ENV=py35-integration-ethtestrpc
    - TOX_ENV=py35-integration-goethereum
    - TOX_ENV=flake8
cache:
  pip: true
install:
  - "travis_retry pip install pip setuptools --upgrade"
  - "travis_retry pip install tox"
before_script:
  - pip freeze
script:
  - tox -e $TOX_ENV --recreate
after_script:
  - cat .tox/$TOX_ENV/log/*.log
